# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-08 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Related2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rename1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.Rename1')),
            ],
        ),
    ]
